export const PANTALLAS = [
  { key: 'home', label: 'Inicio / Dashboard', ACCIONES: ['see', 'export'] },
  { key: 'clientes', label: 'Productores / Clientes', ACCIONES: ['see', 'create', 'update', 'delete', 'export'] },
  { key: 'propiedades', label: 'Propiedades', ACCIONES: ['see', 'create', 'update', 'delete', 'export'] },
  { key: 'empleados', label: 'Empleados', ACCIONES: ['see', 'create', 'update', 'delete', 'export'] },
  { key: 'solicitudes', label: 'Solicitudes', ACCIONES: ['see', 'create', 'update', 'delete', 'export'] },
  { key: 'planificaciones', label: 'Planificación', ACCIONES: ['see', 'create', 'update', 'delete', 'export'] },
  { key: 'inspecciones', label: 'Inspecciones Generales', ACCIONES: ['see', 'create', 'update', 'delete', 'export'] },
  { key: 'acta_silos', label: 'Inspecciones de Silos', ACCIONES: ['see', 'create', 'update', 'delete'] },
  { key: 'avales', label: 'Avales', ACCIONES: ['see', 'create', 'update', 'delete'] },
  { key: 'seguimientos', label: 'Seguimientos', ACCIONES: ['see', 'create', 'update', 'delete'] },
  { key: 'oficinas', label: 'Oficinas', ACCIONES: ['see', 'create', 'update', 'delete'] },
  { key: 'vehiculos', label: 'Vehículos', ACCIONES: ['see', 'create', 'update', 'delete'] },
  { key: 'insumos', label: 'Inventario de Insumos', ACCIONES: ['see', 'create', 'update', 'delete'] },
  { key: 'programas', label: 'Programas', ACCIONES: ['see', 'create', 'update', 'delete'] },
  { key: 'cultivos', label: 'Cultivos', ACCIONES: ['see', 'create', 'update', 'delete'] },
  { key: 'animales', label: 'Animales', ACCIONES: ['see', 'create', 'update', 'delete'] },
  { key: 'plagas', label: 'Plagas', ACCIONES: ['see', 'create', 'update', 'delete'] },
  { key: 'enfermedades', label: 'Enfermedades', ACCIONES: ['see', 'create', 'update', 'delete'] },
  { key: 'reportes', label: 'Reportes y Estadísticas', ACCIONES: ['see', 'export'] },
  { key: 'bitacora', label: 'Bitácora / Auditoría', ACCIONES: ['see', 'export'] },
  { key: 'configuracion', label: 'Configuración Global', ACCIONES: ['see', 'edit'] },
  { key: 'roles', label: 'Gestión de Roles', ACCIONES: ['see', 'create', 'edit', 'delete'] },
  { key: 'usuarios', label: 'Usuarios del Sistema', ACCIONES: ['see', 'create', 'edit', 'delete', 'disable'] },
  { key: 'instancias', label: 'Instancias / Sedes', ACCIONES: ['see', 'create', 'edit', 'delete', 'disable'] },
];

export const ACCIONES = [
  { key: 'see', label: 'Ver' },
  { key: 'create', label: 'Crear' },
  { key: 'update', label: 'Actualizar' },
  { key: 'edit', label: 'Editar' },
  { key: 'delete', label: 'Eliminar' },
  { key: 'disable', label: 'Deshabilitar' },
  { key: 'export', label: 'Exportar' },
  { key: 'clear', label: 'Limpiar' },
];
